version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-node-browsers
        environment:
          DJANGO_SETTINGS_MODULE: config.settings
      - image: circleci/python:2.7-node-browsers
        environment:
          DJANGO_SETTINGS_MODULE: config.settings

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade -r requirements.txt
            pip install tox

      - run:
          command: |
            . venv/bin/activate
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
