version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-node-browsers
        environment:
          DJANGO_SETTINGS_MODULE: config.settings.develop

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade -r requirements.txt
            pip install tox

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -e py36

      - store_artifacts:
          path: test-reports
          destination: test-reports
